/* 
THERE ARE TWO TYPES OF EXPORTS:
1. EXPORT WITH NAME --> BOTH THE EXPORT AND IMPORT VARIABLE NAME HAS TO MATCH
2. EXPORT WITH DEFAULT --> THE EXPORT AND IMPORT VARIABLE NME DOSENT NEED TO BE SAME

YOU CAN HAVE MULTIPLE EXPORT WITH NAME IN A SINGLE FILE, BUT YOU CAN ONLY HAVE ONE EXPORT WITH DEFAULT
*/

export let name = "aarnav"
export let age = 20

let country = "nepal"

export default country
